targets:
  - name: ubisoft.com
    type: "spa"
    url: "https://ubisoft.com"
    interval: 10000
    headers: 
      "x-test": "test"
  - name: coinbase.com
    type: "api"
    url: "https://api.coinbase.com/v2/prices/CAD/spot"
    interval: 10000

exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true

gato:
  chromium:
    headless: true
    ignoreCertificateErrors: true