targets:
  - name: ubisoft.com
    type: "spa"
    url: "https://ubisoft.com"
    interval: 10000


exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true

gato:
  chromium:
    headless: true
    ignoreCertificateErrors: true