targets:
  - name: dna-viewer
    type: "spa"
    url: "https://dna-viewer.ubisoft.org"
    interval: 10000
  - name: uat-dna-viewer
    type: "spa"
    url: "https://uat-dna-viewer.ubisoft.org"
    interval: 10000

exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true

gato:
  chromium:
    ignoreCertificateErrors: true
    headless: false

