targets:
  - name: test-dna-boards
    type: "spa"
    url: "https://test-dna-boards"
    interval: 10000
    performance: true
    headers:
      upgrade-insecure-requests: "0"
  - name: test-dna-wapi
    type: "api"
    url: "https://test-dna-wapi/status"
    interval: 10000
    headers:
      upgrade-insecure-requests: "0"


exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true

gato:
  chromium:
    headless: false
    ignoreCertificateErrors: true