targets:
  # - name: ubisoft.com
  #   type: "spa"
  #   url: "https://ubisoft.com"
  #   interval: 10000
  #   headers: 
  #     "x-test": "test"
  - name: coinbase.com
    type: "api"
    url: "https://test-dna-wapi.ubisoft.org/status"
    interval: 4000
  # - name: coinbase.com error
  #   type: "api"
  #   url: "https://wrong-api.com"
  #   interval: 10000

exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true

gato:
  chromium:
    headless: true
    ignoreCertificateErrors: true