targets:
  - name: ubisoft.com
    type: "spa"
    url: "https://ubisoft.com"
    interval: 60000
    headers: 
      "x-test": "test"
  - name: coinbase.com
    type: "api"
    url: "https://api.coinbase.com/v2/prices/BTC-CAD/buy"
    interval: 5000
  - name: api error
    type: "api"
    url: "https://wrong-api.com"
    interval: 5000

exports:
  - type: httpServer
    port: 8080
  - type: stdout
    pretty: true
  - type: influxDb
    host: "localhost"
    database: "GATO"
    measurement: "load"


gato:
  chromium:
    headless: true
    ignoreCertificateErrors: true